#' title: "PCA"
#' author: "Srilatha Chauah"
#' date: "July 8, 2020"
#' output: PDF file

#' runPCA is used for clustering multiple comparisons efficiently

#' The package used is prcomp

#' The function takes three files as inputs

#' Data 1 - defined as data_matrix, contains gene symbols or ID's along with the expression data as sample1, sample2, .., sampleN in corresponding columns

#' Data 2 - defined as sample_metadata, contains 2 columns, such as the sample ID's (all the column names from 'data_matrix' except for the 1st column are used as the row values here) and the treatment groups corresponding to that sample ID's

#' Data 3 (optional) - defined as data_dictionary, contains only gene symbols or ID's (typically the 1st column from 'data_matrix' with same column name)

#' 'data_matrix' is used as the parameter for runPCA function
#' Example - runPCA(data_matrix)

#' Note: Data matrix file should not contain rows (sample ID's) with all zeros in it (might lead to an error while calculating standard deviation)

#' @import ggpubr
#' @import mixOmics
#' @import readxl

```{r}
runPCA <- function(data_matrix,showlabel = F) {
  pcamat <- do.call("cbind",lapply(data_matrix[,-1],as.numeric))
  pcamat[which(is.na(pcamat)==TRUE)] <- min(pcamat[which(is.na(pcamat)==FALSE)])
  pcamat <- pcamat[-which(apply(data_matrix, 1, sd)==0),]
  pcamat <- pcamat[!(apply(pcamat, 1, function(y) any(y == 0))),]
  pca.res <- prcomp(t(pcamat), scale = T)
  pca.res.sum <- summary(pca.res)
  
  df1 <- cbind(pca.res$x[,1:2],sample_metadata)
  df1[,4] <- as.factor(df1[,4])
  
  x_label <- paste0("PC1 (",round(pca.res.sum$importance[2,1]*100,1),"%)")
  y_label <- paste0("PC2 (",round(pca.res.sum$importance[2,2]*100,1),"%)")
  
  if(showlabel == TRUE) {
    g <-  ggscatter(df1, x = "PC1", y = "PC2",
                    color = names(df1)[4],
                    palette = "aaas",
                    ellipse = TRUE,
                    xlab = x_label,
                    ylab = y_label,size=3, label = "sample_id", repel = T)
  } else {
    g <-  ggscatter(df1, x = "PC1", y = "PC2",
                    color = names(df1)[4],
                    palette = "aaas",
                    ellipse = TRUE,
                    xlab = x_label,
                    ylab = y_label,size=3)
  }
  
  ggexport(g, filename = "pcaplot.pdf",width = 15, height = 12)
}
```

